name: fittracker
description: App completa de fitness, dieta y salud
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Local database
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # Shared preferences
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  
  # Charts
  fl_chart: ^0.66.2
  
  # Image picker
  image_picker: ^1.0.7
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # Date formatting
  intl: ^0.19.0
  
  # UUID
  uuid: ^4.3.3
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true